[package]
name = "rsor"
version = "0.0.0"
description = "Reusable slice of references"
readme = "README.md"
authors = ["Matthias Geier <Matthias.Geier@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"
